[phases.setup]
aptPkgs = ["python3-pip"]
nixPkgs = ["..."]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
start_command = "uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}"
